services:      
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: pokemonreviewapp
      POSTGRES_USER: pokemonreviewapp
      POSTGRES_DB: pokemonreviewapp
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"